services:
  shlink_php_sdk:
    container_name: shlink_php_sdk
    user: 1000:1000
    build:
      context: .
    ports:
      - '8888:8888'
    volumes:
      - ./:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
