name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  ci:
    uses: shlinkio/github-actions/.github/workflows/php-lib-ci.yml@main
    with:
      include-php-eight-two: true
    secrets:
      INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

  integration-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.2', '8.1']
        shlink-version: ['3.3.1', '3.2.1', '3.1.2', '3.0.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
      - run: composer install --no-interaction --prefer-dist ${{ matrix.php-version == '8.2' && '--ignore-platform-req=php' || '' }}
      - run: composer test:integration -- ${{ matrix.shlink-version }}
