name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  ci:
    uses: shlinkio/github-actions/.github/workflows/php-lib-ci.yml@main
    with:
      include-php-eight-two: true
    secrets:
      INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
