name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
        shlink-version: ['4.2', '4.1', '4.0', '3.7', '3.6', '3.5.4', '3.4.0', '3.3.2']
        shlink-api-version: ['3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
      - run: composer install --no-interaction --prefer-dist
      - run: SHLINK_VERSION=${{ matrix.shlink-version }} SHLINK_API_VERSION=${{ matrix.shlink-api-version }} composer test:integration:ci

  ci:
    needs: ['integration-tests'] # Wait for integration tests so that all coverage reports are generated
    uses: shlinkio/github-actions/.github/workflows/php-lib-ci.yml@main
